-- 023: Add company invite codes table
-- Single-use codes generated by company owners/admins to let new users join.

CREATE TABLE IF NOT EXISTS company_invite_codes (
    id          SERIAL PRIMARY KEY,
    company_id  INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    code        VARCHAR(32) NOT NULL,
    role        company_role NOT NULL DEFAULT 'USER',
    created_by  INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    used_by     INTEGER REFERENCES users(id) ON DELETE SET NULL,
    used_at     TIMESTAMP,
    expires_at  TIMESTAMP,
    created_at  TIMESTAMP DEFAULT NOW(),

    CONSTRAINT uq_invite_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS idx_invite_codes_company_id ON company_invite_codes (company_id);
CREATE INDEX IF NOT EXISTS idx_invite_codes_code        ON company_invite_codes (code);
